### ISSUE TITLE
Error: pandoc-citeproc has been disabled because it is deprecated upstream!

### ISSUE THREAD

**Issue by afogel** [Zettlr/zettlr-docs#114]
The docs suggest a `brew install pandoc-citeproc` as a dependency to use Pandoc with Zettlr, however once downloaded, brew throws the following error:
`Error: pandoc-citeproc has been disabled because it is deprecated upstream!`

Is this dependency necessary? If not, I will make a PR to remove that command from the docs.

**Comment by nathanlesage** [comment]
The dependency is no longer necessary since citeproc is part of Pandoc 2.0 and above. So please, feel free to open a PR, since the thing you found is clearly outdated!

**Comment by nathanlesage** [comment]
Oh just saw that this issue is still open – closing as fixed!
