### ISSUE TITLE
Bug on hiding toolbar in distraction free mode.

### ISSUE THREAD

**Issue by LilyTouch** [Zettlr/zettlr-docs#121]
Thank a lot for your work. Zettlr is amazing.

I want to hide toolbar in distraction free mode like describe in <https://docs.zettlr.com/en/core/custom-css/#hide-the-toolbar-in-distraction-free> . But I don’t know why, the code don’t works. However, the code to change the font works.

I am on Linux Mint 19 and zettlr 2.0.1.

Could you help me, please ?

Best regards
Lilian

**Comment by gagarinds** [comment]
same problem

**Comment by hiperterminal** [comment]
> I am on Linux Mint 19 and zettlr 2.0.1.

Same in Ubuntu.

**Comment by nathanlesage** [comment]
There have been changes to how that works between 1.8.9 and 2.0.0. Mainly, changes to the CSS are necessary, but someone needs to find those and update the docs page. Shouldn't take too long following the instructions on how to do custom CSS on the docs (that hasn't changed).

**Comment by LilyTouch** [comment]
I think this issue can be closed with V3.

**Comment by nathanlesage** [comment]
Completely forgot this issue existed, thank you for bringing it up!
