### ISSUE TITLE
[Feature Request] Choose PDF reader

### ISSUE THREAD

**Issue by z4lem** [Zettlr/zettlr-docs#123]
In regarding open PDF files: It would be nice to be able to choose in settings between:
- open file in build-in PDF reader (is it even possible?)
- open file in system-default PDF reader
- choose a PDF reader

Thanks in advance :)

**Comment by nathanlesage** [comment]
Wrong repo, please open on the main repo: https://github.com/Zettlr/Zettlr, since I can't move it on mobile
