### ISSUE TITLE
Cmd/Ctrl-Clicking tags not working

### ISSUE THREAD

**Issue by Phoenicia15** [Zettlr/zettlr-docs#140]
Hey there. I recently upgraded Zettlr for Mac to version 2.2.5. Unfortunately, I seem to have lost a functionality in the new version that worked fine in earlier ones. When I try Cmd-clicking a #tag, either from the tag cloud or from an open note, the search function doesn't work. The program brings up the "Full-Text Search" bar on the left side of the screen, but doesn't transfer the tag text into the search box or actually run the tag search. 

Again, this function worked fine when I was using an older version of Zettlr. I'm not sure if I'm doing something wrong or if the v2.2.5 has a bug in it or something. But can you please help me fix this?

**Comment by nathanlesage** [comment]
Wrong repository. But I just checked, and Cmd/Ctrl-clicking tags works in 2.2.5. Feel free to try to reproduce the issue with as much info as possible and then open an issue on the main repo: https://github.com/Zettlr/Zettlr
