### ISSUE TITLE
Working with multiple cursors in Linux

### ISSUE THREAD

**Issue by stringdom** [Zettlr/zettlr-docs#167]
The documentation claims that in Linux to use Code Mirror's multiple selection you have to use `alt`. While alt is the multiple selection modifier, to create multiple cursors you have to use `ctrl` either alone or with `ctrl+alt`

The current explanation is incorrect and incomplete for Linux. Also have to account that multiple selection works on a per line basis. And a markdown paragraph can be both a really long line or multiple lines. Given that neither Markdown nor Zettlr enforces neither definition, this can create the impression that multi cursor doesn't work.

**Comment by nathanlesage** [comment]
Good catch. I'll make sure to include this in the updated docs.
