### ISSUE TITLE
 zettlr's performance need to improve

### ISSUE THREAD

**Issue by yunnysunny** [Zettlr/zettlr-docs#169]
I recorded a video to show the time zettlr used to open the UI window, to parse the history folders, and to render the tabs last time edited.
And I found that zettlr's performance maybe need to improve.

https://github.com/Zettlr/zettlr-docs/assets/734818/d79a54b8-ceb3-4d52-885b-dc1f6bdd8fbd

Zettlr costs 30s to launch the window, and 60s to show lasted view tabs, and 60s to render the content of tabs.
> I upload a webm video, it not supported on edge now. It plays OK on chrome and firefox.

**Comment by nathanlesage** [comment]
Wrong repository. Open against the main repo. Also, please include more info, "more performance" is not actionable and would be closed there as well.
