### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by thistlillo** [Zettlr/zettlr-docs#172]
I have just installed Zettlr, so I am reading quite a lot of documentation.

The docs are a bit outdated, making learning a bit more difficult than it should. I will add here all the pages that should be revised:

1) https://docs.zettlr.com/en/academic/citations/
The citation database is no longer in "Export", it has its own tab: easy once spotted, but quite disorienting at first.

**Comment by nathanlesage** [comment]
What a timing: Tomorrow I'll release Zettlr 3.0 and I have already an entirely rewritten documentation PR here on the repository that I'll merge tomorrow, so just give it 24 more hours and the documentation will be up to date again (as well as the app itself).
