### ISSUE TITLE
Active Search avoids saving Files

### ISSUE THREAD

**Issue by JensSchwartz** [Zettlr/zettlr-docs#178]
Hi Zettlr Community,

I'm just about to dive into Zettlr.

Found a anoying behavior, which is possibly unintended: While the search pane is active, it's not possible to save changes in open files.
[Ctrl]+[s] doesn't work as same as the command from file menu doesn't.
No error or warning gets displayed - just nothing happens.

Interessting: closing the edited file leads to a Want-to-save-changes dialog.
Confirming with [Yes] closes the file and saves the changes.

That's all for this time - seeing more to come. ^^

Greetings from GER
Jens

Zettlr Version: 3.0.2 (UUID: cdc66a8c-5b7a-42a0-816c-82b1825b3b47)

System: win32 10.0.19045 (architecture: x64)

Build Dependencies
This build was compiled using
Node.js v18.15.0
Electron v25.9.0
Chrome v114.0.5735.289
v8 engine v11.4.183.29-electron.0
Zlib v1.2.13
OpenSSL v1.1.1

**Comment by nathanlesage** [comment]
Wrong repository, please open on the correct one: https://github.com/Zettlr/Zettlr. Thank you.
