### ISSUE TITLE
How to have headings numbered using custom CSS

### ISSUE THREAD

**Issue by internationils** [Zettlr/zettlr-docs#186]
I found this page on how to include CSS:
https://docs.zettlr.com/en/core/custom-css/

...as I am working on a larger document I would like numbered headings, and found this page on how to do it:
https://stackoverflow.com/questions/19999696/are-numbered-headings-in-markdown-rdiscount-possible

...would it be possible to include a working CSS for this on that documentation page?

**Comment by nathanlesage** [comment]
Do you want to number the headings in the editor or during export? Also, please open this issue in the correct repository: https://github.com/Zettlr/Zettlr

**Comment by internationils** [comment]
I would like them in the print preview, and I assumed that the CSS would also include them in the export.
Sorry for opening the issue here, I figured since it's CSS and not a feature request I should request it here with a link to the docs page where it would go. If you want me to reopen as a feature request in the main repo I can do that too, let me know. Thanks!

**Comment by nathanlesage** [comment]
Ah, that should be possible. But please don't use issues for that, go to our Discord channel: https://go.zettlr.com/discord
