### ISSUE TITLE
tex-file not recognised (on Fedora Silverblue / Bluefin)

### ISSUE THREAD

**Issue by Taxicletter** [Zettlr/zettlr-docs#191]
Hi,
I switched from Fedora KDE to Bluefin. Tex as a filetype is not recognised anymore.
The system doesn't show Zettlr as application to open tex-files with. Even a tex-file made with Zettlr, is not visible if you choose open from Zettlr's menu and it's not in the recent files menu.
I'm using the Flatpak version, maybe I could try the AppImage.

I only need Zettlr to recognise the file type, because I have my own export profile. There you have to point to the tex file, but it's not recognised there either.

EDIT: With the app-image, you can open a tex-file with Zettlr, it shows in the menu. It also shows when you choose "open", but there it's greyed out. Exporting doesn't work (but I moved configuration files between the Flatpak and AppImage version and broke something doing so)

**Comment by nathanlesage** [comment]
This is the wrong repository. This repository is exclusively concerned with the Zettlr documentation, not the app itself. If you have issues with the flatpak distribution, please open it on that repository; the link is in the documentation.

**Comment by Taxicletter** [comment]
I'm sorry, I will do that.
