### ISSUE TITLE
translate symbols like "&" will cause issue when paste link from IE edge

### ISSUE THREAD

**Issue by InitialExp** [Zettlr/zettlr-docs#195]
When paste link copied from IE edge address text bar.
Zettlr will translate the link into markdown syntax like "[]()"
Where inside "[]", page title will be put.
Where inside "()", page address will be put.

However, even for the address part, Zetter still do address translating, like translate "&" to "\&". That will cause the link cannot be accessed by open the link.
webpage address should not be translated when pasting.

Hopefully developers can view this issue. Thank you.

**Comment by nathanlesage** [comment]
Please open issues with the app Zettlr itself on the corresponding repository. This is only the documentation. This way: https://github.com/Zettlr/Zettlr
