### ISSUE TITLE
BBT citation pattern variables are documented

### ISSUE THREAD

**Issue by retorquere** [Zettlr/zettlr-docs#2]
The [zettlr docs](https://docs.zettlr.com/academic/citations/) state that 

>  There are two undocumented behaviours in BetterBibTex. First, the available variables you can use to generate your own citation IDs. They are only documented in the JabRef documentation, which you can find here. The second behaviour is that BetterBibTex will automatically use letters from a to z to make citations from the same author in the same year unique (e.g. you'll have something like Harvey2005a, Harvey2005b, Harvey2005c, and so forth).

but this is not the case; both the letter-postfix ("a letter postfix (a, b, c, etc) in case of a clash (this part is always added, you can’t disable it, although you can change it to Zotero-style numeric)") and [all the pattern fields](https://retorque.re/zotero-better-bibtex/citation-keys/#configurable-citekey-generator) are documented at https://retorque.re/zotero-better-bibtex/citation-keys/.

**Comment by nathanlesage** [comment]
Hey, thank you for bringing this to my attention! I missed that part of the documentation, apologies for suggesting the documentation were incomplete. I just fixed that!

**Comment by retorquere** [comment]
No issue -- I don't know how old the zettlr docs are, and a long while ago they weren't documented.

you're using mkdocs for the site? Looks good, I'll have to give that a go.

**Comment by nathanlesage** [comment]
The citation stuff is about 2 to 3 months old, I think. This documentation went live in February, so this might explain why I didn't find anything in your docs, and only on the JabRef site. I was already wondering how this could be possible!

And concerning MkDocs: Yes, it's incredibly easy to set up and customise, with no fancy "use our cool new format to configure that no one has ever heard of!"

If you'd like I can give you a headstart on how to set up a workflow that's incredibly easy to maintain docs with (for instance, the change in the docs needed for this issue went live with one line of Shell script)
