### ISSUE TITLE
The docs mention "snippets", but now this feature is known as "file information"

### ISSUE THREAD

**Issue by fxjkhr** [Zettlr/zettlr-docs#28]
For example, following directions on https://docs.zettlr.com/en/guides/guide-notes/ to configure Zettlr, [step 1 tells you to turn off "Snippets"](https://docs.zettlr.com/en/guides/guide-notes/#step-1-set-up-zettlr-to-look-as-minimal-as-possible)

According to the changelog this setting was renamed in 1.3.0 https://github.com/Zettlr/Zettlr/blob/e298734de1d992482dfc0e6c7a63b1631ce25180/CHANGELOG.md#130

This was confusing, and there are other mentions of "snippets" in the docs

**Comment by nathanlesage** [comment]
Thank you for noticing this! Please feel free to propose the necessary changes over on our repository for the documentation, which we'll gladly merge! https://github.com/Zettlr/zettlr-docs
