### ISSUE TITLE
[CALL FOR CONTRIBUTIONS] Documentation updates for Zettlr 1.7

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/zettlr-docs#29]
As I've outlined on a [lengthy post on reddit](https://www.reddit.com/r/Zettlr/comments/gwpyaf/call_for_contributions_zettlr_documentation_for/), I thought the upcoming 1.7 release of Zettlr would be a great opportunity to bring the documentation up to date. This will reduce the workload for further additions (because we know the documentation is up to date, this'll help our motivation in then keeping it updated further!) and also would be a nice thing to have, as the documentation becomes more and more necessary with each feature. But, as u/enabeh rightly pointed out, I didn't specify how this effort should be facilitated. So here we go!

**In any case, a GitHub account is required, as this is the most time-efficient variant for all of us, so if you don't have one, you can easily create one for free!**

## I want to help — where to start?

First, thank you for wanting to help out! To get started, the best thing is to think about what you'd like to contribute:

1. Skim through all pages in a certain language, and fix typos and grammar
2. Take one page and fully re-write it, removing outdated parts and adding missing ones
3. Add a completely new language (big shoutout on Twitter guaranteed for this!)
4. Create a new page for a missing feature (or take a feature that's grown too big out of an existing page and make a new one)
5. Localize the screenshots

For each points, read the respective headings!

## 1. Skim through a documentation

This is probably the easiest way to contribute (albeit possibly not the most exciting). Nevertheless, chances are that you'll learn something new, and such contributions are also the backbone of any good documentation! To do so, you can either navigate on this repository into one of the language sub-folders (each translation of the documentation resides in its own directory within the `docs`-subdirectory) and read through all the Markdown files here on GitHub. GitHub renders the Markdown perfectly, so you don't need to read the documentation over at docs.zettlr.com! If you're logged in, you can then directly edit a file by clicking the edit button in the top right of the file.

Then, to save the changes, you should "commit" them and open a new Pull Request — then I'll see your PR and will merge it asap so that your changes are visible on the documentation!

You can _also_ go over to the online documentation, and, as soon as you spot something, you can also click on "Edit on GitHub" to directly edit the file, if that suits you more!

## 2. Re-Write a page

Rewriting a page basically works like point 1, but in this case, it would be awesome if you could announce that by commenting here (e.g. "I'm going to re-write the section on Custom CSS completely!") — this way, all other contributors will know that they can leave out that page until you announce here that your PR has been merged by me, so that other people can double-check for typos!

## 3. Add a new language

Adding a new language probably is the most time-consuming process, but it'll help make the documentation more inclusive, because not everybody speaks English, and this will certainly help more people to use the app productively. You can have a look over at https://translate.zettlr.com to see what languages are available for Zettlr, but you can also translate it in any other language that you're proficient in — it's up to you!

The process of how to add a new translation [is outlined in the README](https://github.com/Zettlr/zettlr-docs/blob/master/README.md#create-more-languages) of this repository, but as long as you create a new language sub-directory and translate the English files accordingly, I can modify your PR in case you forget something — don't be afraid to break things, because nothing you could do is unfixable, and the value of your contents outweighs any additional work I might have with it :)

## 4. Add a new page

This could prove useful — I haven't updated the file structure in a long time and there might be quite some instances where a new page would definitely make sense. In that case, just create a new file in the corresponding folder (maybe even a new one? In case of questions, feel free to discuss them here first!) and make sure to link it in the corresponding [config file](https://github.com/Zettlr/zettlr-docs/tree/master/config) (where the navigation is created). You can also link the new file in other pages, depending on where it makes sense. The way these links work is exactly like you would create them in Zettlr, using relative paths.

## 5. Localize the screenshots

Maybe you've noticed that all screenshots are in English, which is because I just screengrabbed them, and placed them in the docs. However, it would be awesome to have a look at them and localize them (they're in the `img` subdirectory of each single translation) by simply taking the same screenshot, but with the correct localization, and simply exchange the corresponding file. And if you add new ones, please! Especially the 5-minutes-quickstart guide could certainly use a refreshment!

***

**Useful Stuff**

Blockquotes are used to indicate info-boxes, that is: To add some info, you can write `> **Note**: Some note` -- many pages make use of this, so just read through some to get to know how it'll look!

Further, make sure to use appropriate heading levels all across the documentation, because this way MkDocs (which we use to build the documentation) can generate text anchors so that we can help other people by sharing links not only to the correct file, but even to the correct heading!

## Further Questions?

Just ask away!

And thanks of course for your help! :)

**Comment by argenos** [comment]
Not sure if this is the right place to ask, or if a new issue would be better.

The section about [formatting the list of references](https://docs.zettlr.com/en/academic/citations/#formatting-the-list-of-references) is a little confusing. Where should I be adding the LaTeX snippet that is mentioned? As part of a LaTeX template?

**Comment by canpolat** [comment]
I see that v1.7.1 does not have the Virtual Directory feature, but the documentation still has it: https://docs.zettlr.com/en/core/virtual-directories/#virtual-directories

Is this a bug or does the documentation needs to be updated about it?

**Comment by nathanlesage** [comment]
> Is this a bug or does the documentation needs to be updated about it?

Documentation is outdated

**Comment by canpolat** [comment]
> Documentation is outdated

I may take a look and see if I can fix it then (if no one else is looking into it).

**Comment by nathanlesage** [comment]
I can assure you, if there is no PR, no one is currently looking into it :D

**Comment by canpolat** [comment]
Sent a PR for the Virtual Directories. Also started skimming the English documentation. I need to learn the tool anyway, might as well fix the typos :)

**Comment by nathanlesage** [comment]
Thanks! I already merged it! I'm also currently rewriting large parts of the docs, so that it's updated, but if you want to edit my texts afterwards and check for typos that would be awesome! I've just finished the `index.md`, and will now gradually move to more parts of the docs!

**Comment by canpolat** [comment]
I went through the first few files, but will hold back with skimming for now, then. Please let me know when you are done so that we do not create conflicts for each other.

**Comment by nathanlesage** [comment]
You can do it! Rewrote most of the documentation, so it's ready for you! :)

If you spot something I missed during this 6h marathon, please feel free to correct the information!

**Comment by fego** [comment]
Hello !
If, for example, in the file "file-list.md " you add a new section or change a sentence, is it automatically added in the other languages, or it has to be updated manually ? I think we have to check manually but I want to be sure. The process to update a language is to check the history of the english translation ?
Regards

**Comment by canpolat** [comment]
It is a manual process. One needs to check the history and find the diffs between versions of the English documentation.

**Comment by the-solipsist** [comment]
The (English) [documentation](https://github.com/Zettlr/zettlr-docs/blob/master/docs/en/reference/markdown-basics.md#zettlr-markdown-additions) lists 3 Zettlr Markdown extensions on top of GFM's extensions. I don't believe this is correct, since Zettlr seems to support footnotes and citations, which come from Pandoc's Markdown.  Is it outdated documentation or is it a misunderstanding on my part?

**Comment by nathanlesage** [comment]
Possibly outdated, as large parts of the documentation. The whole docs need to be rewritten for 1.8 either way due to the numerous changes introduced along the way …
