### ISSUE TITLE
please mention possibility of YAML headers

### ISSUE THREAD

**Issue by boutil** [Zettlr/zettlr-docs#37]
Hi

Could you please add somewhere an explicit mention of YAML frontmatters? I am now using them very often to add title to my individual notes, with a modified tex template, so that the title appears when exporting to pdf.
I found about them by following a long sequence of links. Having them mentionned with a link to the way they can be used in pandoc would be nice.

Thanks.

**Comment by nathanlesage** [comment]
Surely, would you mind looking out where such a mention would fit best in terms of findability? I have difficulties seeing the sole user's perspective as the developer.

**Comment by canpolat** [comment]
Since I'm proofreading the documentation now, I think I can take a look at this. It looks like this will fit under **Core** section before "Custom CSS". But I need to read thru the whole thing first :)

**Comment by nathanlesage** [comment]
@canpolat Already cramped it in this morning, after analyzing the searches users would perform on the documentation — if you'd like feel free to skim the new documentation pages (core/yaml-frontmatter.md, core/print-preview.md, and core/math.md)!
