### ISSUE TITLE
[ENHANCEMENT] Better documenting custom fonts/CSS

### ISSUE THREAD

**Issue by nyanpasu64** [Zettlr/zettlr-docs#40]
## Description

Zettlr's docs should better explain how to create your own CSS customizations.

## Proposed Changes

I just downloaded Zettlr to see how it worked, and compare it against Typora (another WYSIWYG Markdown editor). I didn't like the initial appearance, but found several roadblocks to customizing the styles.

- The docs at https://docs.zettlr.com/en/core/custom-css/#custom-css are quite incomplete. It explains how all rules are rooted at body/body.dark. and supplies a list of all classes, but does not specify what rules exist, or what hierarchy the elements form.
    - (I don't know if this needs explaining. When customizing websites, I'm used to using Developer Tools to figure things out.)
    - There is a large "grab bag" of pre-written GUI tweaks. Maybe these could be program options instead, I'm not sure.
    - Without F12, I don't know what elements I can style, how they're arranged in a tree, or what existing rules exist.
- https://docs.zettlr.com/en/core/custom-css/#custom-css should explain how to open developer tools.
    - Currently, that link doesn't mention developer tools at all. I had to search to find a different doc page, https://docs.zettlr.com/en/get-involved/#devtools-development-tools, which mentions you need to enable "debug-mode". I searched the docs, but couldn't find how to enable debug mode. I eventually discovered it's via Preferences, Advanced tab (where it's called "debug mode" without a hyphen).

----

Copied from https://github.com/Zettlr/Zettlr/issues/982.

**Comment by nathanlesage** [comment]
Thanks for porting this issue! I'm always pretty much in my dev-mind and hence not that good in keeping the docs updated, so in case you have some free time, I'd welcome a PR containing good changes to the points mentioned by you! :)

Depending on my time, I may even be able to help a little bit …

**Comment by nathanlesage** [comment]
Just had the time to update the documentation accordingly; now it explains first how to use the developer tools, and second which rules you should use to style specific elements. I basically brain-dumped my own workflow when I tweak the CSS, and it's fairly straight forward! In case there's room for improvement, just update the documentation and open a PR!

**Comment by nyanpasu64** [comment]
Thanks, https://docs.zettlr.com/en/core/custom-css/#tips-for-finding-selectors looks very well documented now!
