### ISSUE TITLE
Open second tab when no document is open

### ISSUE THREAD

**Issue by ajlewis2** [Zettlr/zettlr-docs#41]
Possible bug:
Open program with no document open.
Open a document from the left side panel
Attempt to open a second document with Ctrl Left Click
The new doc opens in the one tab

Work around:
Before opening the new document, edit the one open document.
Then Ctrl Left Click to open second document and it goes into a new tab
Simply Saving the first document without editing does not work.

It seems that Ctrl Click should open a new doc in a new tab without editing the first document.

I'm running the Debian version on Linux Mint 18.3

**Comment by nathanlesage** [comment]
> Attempt to open a second document with Ctrl Left Click
> The new doc opens in the one tab

This is totally expected; the tab transiency, I still haven't been able to add this to the docs, see https://github.com/Zettlr/zettlr-docs/issues/38
