### ISSUE TITLE
Editing tables created prior to adopting Zettlr

### ISSUE THREAD

**Issue by piccolbo** [Zettlr/zettlr-docs#52]
I have a bunch of tables created in some editor and would like to see or edit them in Zettlr after importing the document, is there a way? Thanks

**Comment by nathanlesage** [comment]
If these are tables supported by Pandoc, the Table Editor should automatically pick them up: I'd suggest you just give it a try and import a document. If something breaks, feel free to report this as a bug, but please make sure to include as much information as possible!

**Comment by piccolbo** [comment]
You are right, it's only with a particularly big one that I see this problem. Probably some formatting error.

**Comment by nathanlesage** [comment]
> Probably some formatting error.

Yeah, Markdown tables can really be a pain sometimes :/

**Comment by piccolbo** [comment]
I think there were two fused lines. But when I reopened the file, the table again was not formatted. I just added a newline at the end, and back on track it was. So maybe a combination of the two: you need a consistent number of columns and you need some separation below (and above?). It is offputting from a user perspective. If there were some red marks like linters in IDES, or a partially formatted table or anything to guide the user it would be awesome. I solved the problem when I realized that by breaking the table in two chunks, the first parsed fine. Moved the break further down until it didn't. There were the two offending lines. But for users who don't know binary search ;) it doesn't look it's a viable approach.

**Comment by nathanlesage** [comment]
> If there were some red marks like linters in IDES, or a partially formatted table or anything to guide the user it would be awesome.

Absolutely! The TableEditor needs some refreshments either way, as there are still other things that should be improved upon. (However, N.B.: you shouldn't do Markdown Tables either way if they are too complex, because then it makes more sense to just import them from some other file format and glue them into the correct place using the Project feature … well, I guess I need to finally get doing those tutorial videos …)
