### ISSUE TITLE
[ENHANCEMENT] Add documentation how to change header styles

### ISSUE THREAD

**Issue by inquisitiv3** [Zettlr/zettlr-docs#55]
I've been trying to change the size of the headers to the body font size, but I couldn't figure it out. I tried to inspect the elements, but couldn't find the obvious element/id/class. Context: I'm not a web developer, and have done any web development in a long time.

The information would fit as a subsection to _Using a Custom Font with Zettlr_[0], or a section directly after.

[0] https://docs.zettlr.com/en/core/custom-css/#using-a-custom-font-with-zettlr

**Comment by canpolat** [comment]
I'm not sure I understood what you mean, but here is an attempt to address the question. You can switch to debug mode (Preferences > Advanced > Enable Debug Mode) and the right click on an element to inspect it (screenshot 1). This will open the developer tools. If you select the **Elements** tab, you can see the elements that are in the document. I suppose, in your case, you are looking for `cm-header-1`, `cm-header-2`, etc. (screenshot 2).

When it comes to documentation, [Tips for finding selectors](https://docs.zettlr.com/en/core/custom-css/#tips-for-finding-selectors) gives a general description of how these classes can be found. It may be difficult to maintain if one tries to do into too much detail, I would guess.

**Screenshot 1**
![image](https://user-images.githubusercontent.com/459891/87793791-04ae0200-c846-11ea-8d9f-513dc2d2c5eb.png)


![image](https://user-images.githubusercontent.com/459891/87793703-e47e4300-c845-11ea-9196-2a7eea575fb5.png)

**Comment by inquisitiv3** [comment]
Thank you! It seems that `cm-header-*` is the classes I want to change. What's the best way to override them if I only want them to have the same font-size as body text? Copy paste code and change that one value?

I've only basic experience with web development, so I'm clueless on what to do.

**Comment by canpolat** [comment]
I don't really know. Perhaps try something like this?

```css
.cm-header-1 {
  font-size: 0.5em;
}

.cm-header-2 {
  font-size: 0.5em;
}

(...)
```

**Comment by nathanlesage** [comment]
@canpolat or @inquisitiv3 feel free to propose this explanation in addition to the ["Tips for finding selectors"](https://docs.zettlr.com/en/core/custom-css/#tips-for-finding-selectors)-section in the docs, including images if you like!

**Comment by inquisitiv3** [comment]
> I don't really know. Perhaps try something like this?
> 
> **Edit:** You only need to overwrite the value you are interested in. In this case `font-size`. You don't need to copy the other values for this to work. They will be inherited from the existing CSS files as usual.
> 
> ```css
> .cm-header-1 {
>   font-size: 0.5em;
> }
> 
> .cm-header-2 {
>   font-size: 0.5em;
> }
> 
> (...)
> ```

Thanks! But it seems that the `em` value differs between the headers? If I add

```
.cm-header-6 {
	font-size: 0.5em;
}
```
I get extremely small level 6 headers (smaller than the body text). I would also like to have the links in headers to the same size as the regular text. The classes applied to links seem to be `cm-zkn-link-formatting` and `cm-zkn-link`. But changes apply globally, which screw up link in the body text?

**Comment by canpolat** [comment]
I'm not very good with CSS, either, but could you perhaps try `rem` instead of `em`? According to w3schools.com "The rem unit sets the font-size relative to the browsers base font-size, and will not inherit from its parents." More info: https://www.w3schools.com/CSSref/css_units.asp

**Comment by nathanlesage** [comment]
Ah, yes, it's `size-header-*` where * is [1-6]! Just looked it up in the plugin!

**Comment by inquisitiv3** [comment]
Thanks! This do what I want

```
.CodeMirror .size-header-1,
.CodeMirror .size-header-2,
.CodeMirror .size-header-3,
.CodeMirror .size-header-4,
.CodeMirror .size-header-5,
.CodeMirror .size-header-6 {
	font-size: 1em;
}
```

Is there a nice way to express the same without having to repeat `.CodeMirror` six times?

**Comment by nathanlesage** [comment]
> Is there a nice way to express the same without having to repeat .CodeMirror six times?

Not for CSS, unfortunately.
