### ISSUE TITLE
Consider front matter in project metadata

### ISSUE THREAD

**Issue by GrazingScientist** [Zettlr/zettlr-docs#79]
I find front matter very convenient, because you spot them on first sight and they are easily changeable while also being very expandable (e.g. author + affiliation).

It would be great, if the font matter given in a markdown file within a Zettlr project would be considered for the project export. So, I would like to give title, author etc. in the front matter and not in the project settings.

Thanks for providing this cool editor!

Cheers,

Adrian

**Comment by the-solipsist** [comment]
Hi @GrazingScientist. This is the Zettlr documentation repository.  I see that you have also opened an issue on the Zettlr repository.  So please close this one.

**Comment by GrazingScientist** [comment]
Sorry! I did not realize that!
