### ISSUE TITLE
Document doesn't respond to scrolling when the mouse is to the left of the document

### ISSUE THREAD

**Issue by LePeti** [Zettlr/zettlr-docs#94]
Hi!

Tiny annoyance here: there is a strip between the left margin of a document and the side bar, which is white, thus not visually separated from the document itself. I often found myself trying to scroll through a document when my cursor was located on that strip without much success. It'd help if I could scroll in that case too or any visual cue about where the document ends on the left side, for example a thin line.

![Screenshot 2021-01-24 at 14 52 27](https://user-images.githubusercontent.com/19508797/105632555-07705c00-5e54-11eb-8bfe-a9ffb09f5dea.png)

Again, just a small thing, otherwise great app!

**Comment by nathanlesage** [comment]
Hey, thanks for reporting! Unfortunately, wrong repository ;)

I'll add that to the roadmap for Zettlr 2.0.
